version: "3.7"
services:
  app:
    image: docker.joestrong.co.uk/movienight-app:latest
    build:
      dockerfile: ./docker/app/Dockerfile
      context: .
  php:
    image: docker.joestrong.co.uk/movienight-php:latest
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .

