app:
  container_name: movienight
  build: ./docker/app
  links:
   - php
  volumes:
   - .:/web
php:
  container_name: movienight-php
  build: ./docker/php
  volumes:
   - .:/web
  links:
   - mysql
mysql:
  container_name: movienight-mysql
  image: mysql:5
  environment:
   - MYSQL_ROOT_PASSWORD=%4VZAs-X@vfc)sa1
  ports:
   - "3306:3306"
