name: Deploy
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - feature/github-actions

jobs:
  build:
    name: Composer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache composer dependancies
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - uses: docker://tmaier/docker-compose:latest
        run: |
          docker-compose -f docker-compose.build.yml build
          docker push docker.joestrong.co.uk/movienight-app:latest
  deploy:
    name: Deploy to K8
    needs: buildImage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Push to K8
        uses: docker://atlassian/pipelines-kubectl:1.16.3
        run: |
          echo -n "$KUBERNETES_CLUSTER_CERTIFICATE" | base64 -d > ca.cert
          kubectl config set-cluster $KUBERNETES_CLUSTER --server=$KUBERNETES_SERVER --certificate-authority=ca.cert
          kubectl config set-context my-context --cluster=$KUBERNETES_CLUSTER
          kubectl config use-context my-context
          kubectl apply --token=$KUBERNETES_TOKEN -f k8/deployment.yml
          kubectl apply --token=$KUBERNETES_TOKEN -f k8/service.yml

